mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.cpl.tsl.bean
server:
  port: 8181
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        maxPoolSize: 100
        minPoolSize: 5
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/tsl?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
      ds2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        maxPoolSize: 100
        minPoolSize: 5
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/tsl_read?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
      names: ds1,ds2
    masterslave:
      load-balance-algorithm-type: round_robin
      master-data-source-name: ds1
      name: ms
      slave-data-source-names: ds2
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: ds1
