# 服务名称
applicationName: tsl
server:
  port: 8181
#  context-path: /tsl
spring:
  #  resources:
  #    static-locations: classpath:html/
  aop:
    auto: true
    proxy-target-class: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#设置日志级别打印出sql
logging:
  level:
    com:
      cpl:
        tsl: debug
swagger: true
